version: '3'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db-development:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
        - ./backend/db/init.sql:/data/application/init.sql